---
title: "Testing Guide"
author: "Andy Nicholls"
date: "05/10/2020"
output: html_document
---

Examples taken from [https://r-pkgs.org/tests.html](https://r-pkgs.org/tests.html).

```{r startup, include = FALSE, message = FALSE, warning = FALSE}
# Settings
knitr::opts_chunk$set(
  fig.align = 'center',
  comment=NA,
  message = FALSE)

# Setup
library(testthat)
```

# Overall Structure

```{r}
context("String length")
library(stringr)

test_that("str_length is number of characters", {
  expect_equal(str_length("a"), 1)
  expect_equal(str_length("ab"), 2)
  expect_equal(str_length("abc"), 3)
})
#> Test passed 🎊

test_that("str_length of factor is length of level", {
  expect_equal(str_length(factor("a")), 1)
  expect_equal(str_length(factor("ab")), 2)
  expect_equal(str_length(factor("abc")), 3)
})
#> Test passed 😸

test_that("str_length of missing is missing", {
  expect_equal(str_length(NA), NA_integer_)
  expect_equal(str_length(c(NA, 1)), c(NA, 1))
  expect_equal(str_length("NA"), 2)
})
#> Test passed 🥳
```

# The `expect_*` Functions

To check results using testthat we use the  `expect_*` functions.  Here is a complete list of the available functions:

```{r all_expects}
apropos("expect_")
```

# Example functions

Numeric comparisons:

```{r numeric, eval = FALSE}
# Equality
expect_equal(10, 10)
expect_equal(10, 10 + 1e-7)
expect_equal(10, 11) # Failure

# Exact match
expect_equal(10, 10 + 1e-7)
expect_identical(10, 10 + 1e-7) # Failure

# Ignoring attributes
expect_equal(data.frame(x = 1:2, y = c("a", "b")), 
             tibble(x = 1:2, y = c("a", "b")))             # Failure
expect_equivalent(data.frame(x = 1:2, y = c("a", "b")), 
                  tibble(x = 1:2, y = c("a", "b")))
```

Character comparisons:

```{r character, eval = FALSE}
# Equality
string <- "Testing is fun!"
expect_match(string, "Testing") 
# Additional arguments are passed to grepl:
expect_match(string, "testing", ignore.case = TRUE)
```

Structure:

```{r structure}
# Structure
a <- list(1:10, letters)
expect_output(str(a), "List of 2")
expect_output(str(a), "int [1:10]", fixed = TRUE)

# Class
model <- lm(mpg ~ wt, data = mtcars)
expect_is(model, "lm")
```

Messages:

```{r messages}
expect_warning(log(-1), "NaNs produced")
expect_error(1 / "a", "non-numeric argument")
```

