---
title: "Test Report"
author: "Emma Martin, Andy Nicholls"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
    css: ./css/report.css
---
<!-- Edit header ^ -->

# Package: riskydplyr

```{r startup, include = FALSE, message = FALSE, warning = FALSE}
sess <- sessioninfo::session_info()
platform <- sess$platform

#Settings
knitr::opts_chunk$set(
  fig.align = 'center',
  echo = FALSE,
  comment=NA,
  message = FALSE)

# Set-up
filepath <- "./testthat"
```

<!-- Run tests -->
```{r run_testthat}
source("./code/run_tests.R")
```

<!-- Summarise tests -->
```{r summary_report}
source("./code/val_reporter.R")
```

## Test Completion

High level test results:

```{r summary_table}
result_overall %>%
  knitr::kable()
```

# Environment Details

## Platform

Details of testing platform:

```{r platform}
platform
```

## Test Cases

<!-- Replace directory with file containing test scripts -->
Test directory
```{r testdir, asis=TRUE}
cat(filepath)
```

Files executed:
```{r testdir_files}
test_scripts <- list.files(filepath)
for(test in test_scripts) cat(test, fill=TRUE)
```


# Test Results

## Results Summary

Summary of number of tests conducted and number of failures: 

```{r result_byreq}
knitr::kable(result_byreq)
```
## Test Details

### Detailed Summary

```{r result_detail}
knitr::kable(result_detail)
```


### Test Failures

Details of failed tests:
```{r error_report}
source("./code/val_reporter_err.R")
```

